import logging

import psycopg2

from odoo import api, fields, models
from odoo.exceptions import AccessError, ConcurrencyError, UserError, ValidationError

from .geo import (
    CLOCK_TOLERANCE,
    FUTURE_TOLERANCE,
    MAX_START_AGE,
    check_position,
    format_utc,
    haversine_km,
    parse_utc,
    to_float,
)

_logger = logging.getLogger(__name__)

# First key of the transaction-level advisory lock serialising "start a work
# day" per employee (second key: the employee id).
_START_LOCK_NAMESPACE = 0x5744  # "WD"

# Set once at creation; never changed afterwards, not even by an administrator.
_IMMUTABLE_FIELDS = frozenset(
    {"client_uid", "employee_id", "started_at", "start_latitude", "start_longitude", "device_id"}
)


class DhWorkSession(models.Model):
    """One employee work day: the envelope around every GPS point recorded
    between "Start Work Day" and "End Work Day", including the movement
    between visits. Visits happen inside it; they are not it."""

    _name = "dh.work.session"
    _description = "Employee Work Day"
    _order = "started_at desc, id desc"

    name = fields.Char(compute="_compute_name", store=True)
    client_uid = fields.Char(
        string="Client UID",
        readonly=True,
        copy=False,
        help="Generated by the app before the server knew the work day; makes starting idempotent.",
    )
    employee_id = fields.Many2one(
        "hr.employee",
        required=True,
        readonly=True,
        index=True,
        ondelete="restrict",
        default=lambda self: self.env.user.employee_id,
    )
    user_id = fields.Many2one(related="employee_id.user_id", store=True, index=True)
    company_id = fields.Many2one(related="employee_id.company_id", store=True, index=True)
    started_at = fields.Datetime(required=True, readonly=True, index=True, default=fields.Datetime.now)
    ended_at = fields.Datetime(readonly=True)
    state = fields.Selection(
        [("active", "Active"), ("completed", "Completed")],
        required=True,
        readonly=True,
        default="active",
        index=True,
    )
    start_latitude = fields.Float(digits=(10, 7), readonly=True)
    start_longitude = fields.Float(digits=(10, 7), readonly=True)
    end_latitude = fields.Float(digits=(10, 7), readonly=True)
    end_longitude = fields.Float(digits=(10, 7), readonly=True)
    device_id = fields.Char(readonly=True)
    location_ids = fields.One2many("dh.work.location", "session_id", string="GPS Points", readonly=True)
    location_count = fields.Integer(compute="_compute_track", string="Points")
    tracked_distance_km = fields.Float(compute="_compute_track", digits=(12, 3), string="Distance (km)")

    # The database, not the app, guarantees one open work day per employee:
    # two simultaneous "start" requests cannot both commit.
    _one_active_per_employee = models.UniqueIndex(
        "(employee_id) WHERE state = 'active'",
        "An employee can only have one active work day.",
    )
    _client_uid_per_employee = models.UniqueIndex(
        "(employee_id, client_uid) WHERE client_uid IS NOT NULL",
        "This work day was already started.",
    )
    _ended_after_started = models.Constraint(
        "CHECK (ended_at IS NULL OR ended_at >= started_at)",
        "A work day cannot end before it started.",
    )
    _completed_has_end = models.Constraint(
        "CHECK (state != 'completed' OR ended_at IS NOT NULL)",
        "A completed work day needs an end time.",
    )

    @api.depends("employee_id", "started_at")
    def _compute_name(self):
        for session in self:
            day = fields.Datetime.to_string(session.started_at)[:10] if session.started_at else ""
            session.name = f"{session.employee_id.name or ''} {day}".strip()

    @api.depends("location_ids.latitude", "location_ids.longitude", "location_ids.logged_at")
    def _compute_track(self):
        for session in self:
            points = session.location_ids.sorted(lambda p: (p.logged_at, p.id))
            distance = 0.0
            for previous, current in zip(points, points[1:]):
                distance += haversine_km(
                    previous.latitude, previous.longitude, current.latitude, current.longitude
                )
            session.location_count = len(points)
            session.tracked_distance_km = round(distance, 3)

    # ------------------------------------------------------------------
    # ORM guards: apply to the API and to any other caller (call_kw, UI).
    # ------------------------------------------------------------------

    @api.model_create_multi
    def create(self, vals_list):
        now = fields.Datetime.now()
        for vals in vals_list:
            employee = self.env["hr.employee"].browse(vals.get("employee_id") or self.env.user.employee_id.id)
            if not employee:
                raise UserError(self.env._("Your user is not linked to an employee, so no work day can be recorded."))
            vals["employee_id"] = employee.id
            if not self.env.su and employee.sudo().user_id != self.env.user:
                raise AccessError(self.env._("You can only start your own work day."))
            if vals.get("state", "active") != "active" and not self.env.su:
                raise UserError(self.env._("A work day can only be created as active."))
            started_at = parse_utc(self.env, vals.get("started_at"), self.env._("The start time")) or now
            if started_at > now + FUTURE_TOLERANCE:
                raise ValidationError(self.env._("A work day cannot start in the future."))
            if started_at < now - MAX_START_AGE and not self.env.su:
                raise ValidationError(self.env._("A work day started more than 7 days ago can no longer be uploaded."))
            vals["started_at"] = started_at
            self._check_optional_position(vals, "start_latitude", "start_longitude")
            overlapping = self.sudo().search_count(
                [
                    ("employee_id", "=", employee.id),
                    ("state", "=", "completed"),
                    ("ended_at", ">", started_at + CLOCK_TOLERANCE),
                ],
                limit=1,
            )
            if overlapping:
                raise ValidationError(self.env._("This work day would start inside a work day that is already completed."))
        return super().create(vals_list)

    def write(self, vals):
        if "state" in vals and vals["state"] not in ("active", "completed"):
            raise ValidationError(self.env._("Unknown work day state."))
        for session in self:
            # No bypass, not even for the superuser: a closed day stays closed.
            if session.state == "completed" and vals.get("state") == "active":
                raise UserError(self.env._("A completed work day cannot be reopened."))
        if not self.env.su:
            if _IMMUTABLE_FIELDS & set(vals):
                raise UserError(self.env._("The start of a work day cannot be changed."))
            for session in self:
                if session.state == "completed":
                    raise UserError(self.env._("A completed work day cannot be changed."))
                if session.employee_id.sudo().user_id != self.env.user and not self.env.user.has_group(
                    "dh_visit_management.group_visit_admin"
                ):
                    raise AccessError(self.env._("You can only end your own work day."))
        if vals.get("state") == "completed" and not vals.get("ended_at"):
            vals = dict(vals, ended_at=fields.Datetime.now())
        if vals.get("ended_at"):
            ended_at = parse_utc(self.env, vals["ended_at"], self.env._("The end time"))
            if ended_at > fields.Datetime.now() + FUTURE_TOLERANCE:
                raise ValidationError(self.env._("A work day cannot end in the future."))
            vals = dict(vals, ended_at=ended_at)
        self._check_optional_position(vals, "end_latitude", "end_longitude")
        return super().write(vals)

    def unlink(self):
        if not self.env.su and not self.env.user.has_group("base.group_system"):
            raise UserError(self.env._("Work days cannot be deleted."))
        return super().unlink()

    def _check_optional_position(self, vals, lat_key, lng_key):
        if lat_key not in vals and lng_key not in vals:
            return
        latitude = to_float(self.env, vals.get(lat_key), lat_key)
        longitude = to_float(self.env, vals.get(lng_key), lng_key)
        if latitude is None and longitude is None:
            vals[lat_key] = vals[lng_key] = 0.0
            return
        if latitude is None or longitude is None:
            raise ValidationError(self.env._("Latitude and longitude must be sent together."))
        check_position(self.env, latitude, longitude)
        vals[lat_key], vals[lng_key] = latitude, longitude

    # ------------------------------------------------------------------
    # Business operations used by /api/workday/*
    # ------------------------------------------------------------------

    @api.model
    def _current_employee(self):
        employee = self.env.user.employee_id
        if not employee:
            raise UserError(self.env._("Your user is not linked to an employee, so no work day can be recorded."))
        return employee

    @api.model
    def start_day(self, client_uid, latitude=None, longitude=None, started_at=None, device_id=None):
        """Opens the caller's work day and returns `(session, created)`.

        Idempotent: the same `client_uid` returns the work day it created. If
        another work day is still open it is returned instead of opening a
        second one. Concurrent calls for one employee are serialised by an
        advisory lock, and the partial unique index is the final guard."""
        employee = self._current_employee()
        client_uid = (str(client_uid).strip() if client_uid else "")[:64]
        if not client_uid:
            raise ValidationError(self.env._("client_uid is required."))
        self.env.cr.execute("SELECT pg_advisory_xact_lock(%s, %s)", (_START_LOCK_NAMESPACE, employee.id))
        existing = self.search([("employee_id", "=", employee.id), ("client_uid", "=", client_uid)], limit=1)
        if existing:
            return existing, False
        active = self.search([("employee_id", "=", employee.id), ("state", "=", "active")], limit=1)
        if active:
            return active, False
        vals = {
            "employee_id": employee.id,
            "client_uid": client_uid,
            "started_at": started_at,
            "device_id": (str(device_id)[:128] if device_id else False),
        }
        if latitude not in (None, False) or longitude not in (None, False):
            vals.update(start_latitude=latitude, start_longitude=longitude)
        try:
            with self.env.cr.savepoint():
                return self.create(vals), True
        except psycopg2.errors.UniqueViolation:
            # A concurrent request committed first. Odoo runs requests in
            # REPEATABLE READ, so this transaction cannot see that row: let
            # the HTTP layer (odoo.service.model.retrying) run the request
            # again on a fresh snapshot, where it finds and returns that day.
            _logger.info("work day start for employee %s raced; retrying", employee.id)
            raise ConcurrencyError("concurrent work day start") from None

    def end_day(self, ended_at=None, latitude=None, longitude=None):
        """Completes the work day. Returns False when it already was
        completed (a retried request), True otherwise."""
        self.ensure_one()
        # Blocks until in-flight point uploads (FOR SHARE) have committed.
        self.env.cr.execute("SELECT state FROM dh_work_session WHERE id = %s FOR UPDATE", [self.id])
        self.invalidate_recordset(["state", "ended_at"])
        if self.state == "completed":
            return False
        vals = {"state": "completed", "ended_at": parse_utc(self.env, ended_at, self.env._("The end time")) or fields.Datetime.now()}
        if vals["ended_at"] < self.started_at:
            vals["ended_at"] = self.started_at
        if latitude not in (None, False) or longitude not in (None, False):
            vals.update(end_latitude=latitude, end_longitude=longitude)
        self.write(vals)
        return True

    def _lock_for_points(self):
        """Locks the work day against being ended while points are added, and
        refuses points into a completed day."""
        self.ensure_one()
        self.env.cr.execute("SELECT state FROM dh_work_session WHERE id = %s FOR SHARE", [self.id])
        row = self.env.cr.fetchone()
        if not row or row[0] != "active":
            raise UserError(
                self.env._("The work day %(name)s is completed; no position can be added to it.", name=self.name)
            )

    def _api_dict(self):
        self.ensure_one()
        return {
            "id": self.id,
            "client_uid": self.client_uid or False,
            "employee_id": self.employee_id.id,
            "employee_name": self.employee_id.name,
            "started_at": format_utc(self.started_at),
            "ended_at": format_utc(self.ended_at),
            "state": self.state,
            "start_latitude": self.start_latitude,
            "start_longitude": self.start_longitude,
            "end_latitude": self.end_latitude,
            "end_longitude": self.end_longitude,
            "device_id": self.device_id or False,
            "location_count": self.location_count,
            "tracked_distance_km": self.tracked_distance_km,
        }
