// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhRM22Vacu2zSvhaQc-cDdKgVRpeU-vo',
    appId: '1:1029698829865:web:7d15962743623c25e9a638',
    messagingSenderId: '1029698829865',
    projectId: 'visits-app1',
    authDomain: 'visits-app1.firebaseapp.com',
    storageBucket: 'visits-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsiNAwtOtsXodNM980mbovvZ11tqL8Ng',
    appId: '1:1029698829865:android:c1475b63c6bcee0fe9a638',
    messagingSenderId: '1029698829865',
    projectId: 'visits-app1',
    storageBucket: 'visits-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qMPWbDVWJc4rQUwaKhcoCdFhLYFcAUc',
    appId: '1:1029698829865:ios:276bd3f4bf93c508e9a638',
    messagingSenderId: '1029698829865',
    projectId: 'visits-app1',
    storageBucket: 'visits-app1.firebasestorage.app',
    iosBundleId: 'net.digitalharbor.visits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2qMPWbDVWJc4rQUwaKhcoCdFhLYFcAUc',
    appId: '1:1029698829865:ios:77df2cec7e0b9ffde9a638',
    messagingSenderId: '1029698829865',
    projectId: 'visits-app1',
    storageBucket: 'visits-app1.firebasestorage.app',
    iosBundleId: 'com.example.locationGps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhRM22Vacu2zSvhaQc-cDdKgVRpeU-vo',
    appId: '1:1029698829865:web:c55aa562bd41f45be9a638',
    messagingSenderId: '1029698829865',
    projectId: 'visits-app1',
    authDomain: 'visits-app1.firebaseapp.com',
    storageBucket: 'visits-app1.firebasestorage.app',
  );
}
